### ISSUE TITLE
milestonesのページの修正 to 甲斐瑛さん

### ISSUE THREAD

**Issue by hagukky** [hagukky/hagukky.github.io#18]
マサキ君が使い方を書いてなかったので、次の２文を追加してください。
（マイルストーンの追加、編集、削除は、マイルストーン管理ページから実行できます。
イシュー（プルリクエスト）の一覧ページを表示し、「Milestones」をクリックします。）

あと、トップへを戻るの直してください。

以上です。
ご確認のほどよろしくお願いします。

**Comment by zapmakesmehappy** [comment]
この2文はどこに追加したらよいですか？

**Comment by Osukaaa** [comment]
俺のせいにしないでください

**Comment by hagukky** [comment]
確認いたしました。ありがとうございます。
